version: '3.4'

services:
  dogtrekking_eu_grpc:
    image: ${docker_registry-}backend
    build:
      context: .
      dockerfile: DogtrekkingCzGRPCService/Dockerfile
    ports:
      - 4080:80
      - 4443:443
  dogtrekking_eu: 
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: DogtrekkingCzApp/Dockerfile
    ports:
      - 5080:80
      - 5443:443
