version: '3.4'

services:
  # For development - there is a need to configure certificates
  # -----------------------------------------------------------
  # Windows => Linux
  # dotnet dev-certs https --clean
  # dotnet dev-certs https -ep "$env:USERPROFILE\.aspnet\https\aspnetapp.pfx"  -p cert_password
  # dotnet dev-certs https --trust
  #
  # Linux
  # dotnet dev-certs https --clean
  # dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p cert_password
  # dotnet dev-certs https --trust
  petsontrail_grpc:
    image: petsontrail_server_grpc
    build:
      context: .
      dockerfile: API.GRPCService/Dockerfile
    ports:
      - 4080:80
      - 4443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cert_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/backup:/backup
      
  petsontrail_webapi:
    image: petsontrail_server_api
    build:
      context: .
      dockerfile: API.WebApiService/Dockerfile
    ports:
      - 3080:80
      - 3443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cert_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/backup:/backup
      
  petsontrail_app: 
    image: petsontrail_client_app
    build:
      context: .
      dockerfile: frontend/PetsOnTrailApp/Dockerfile
    ports:
      - 1443:443
      - 1080:80
      
  dtdata_db:
    image: mongo:latest
    container_name: data_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: petsontrailDb
    ports:
      - 27017:27017
    volumes:
      - data_petsontrail_db:/data/db
    restart: always
   
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycl0ak
      POSTGRES_USER: keycl0ak
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    restart: always

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycl0ak
      DB_USER: keycl0ak
      DB_PASSWORD: password
      KEYCLOAK_USER: administrat0r
      KEYCLOAK_PASSWORD: asc88a8c0ssssqs
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
      
  mail:
    image: bytemark/smtp
    restart: always

  # MessageQueue not necessary yet
  #mq:
  #  image: rabbitmq:management
  #  container_name: message-queue
  #  ports:
  #    - 15672:15672
  #    - 5672:5672
  #    - 5671:5671
  #  volumes:
  #    - data_mq:/var/lib/rabbitmq
      
volumes:
  data_petsontrail_db:
  data_mq:
  postgres_data:
      driver: local
  
  

