//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogtrekkingCzApp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogtrekkingCzApp.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new action.
        /// </summary>
        internal static string Add_new_action {
            get {
                return ResourceManager.GetString("Add new action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update action.
        /// </summary>
        internal static string Add_Update_action {
            get {
                return ResourceManager.GetString("Add/Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action.
        /// </summary>
        internal static string Delete_action {
            get {
                return ResourceManager.GetString("Delete action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of action.
        /// </summary>
        internal static string Description_of_action {
            get {
                return ResourceManager.GetString("Description of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled races.
        /// </summary>
        internal static string Enrolled_races {
            get {
                return ResourceManager.GetString("Enrolled races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string Loading____ {
            get {
                return ResourceManager.GetString("Loading ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What &amp; who.
        /// </summary>
        internal static string Name___description_of_action {
            get {
                return ResourceManager.GetString("Name & description of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_of_action {
            get {
                return ResourceManager.GetString("Name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region, city.
        /// </summary>
        internal static string Region__city {
            get {
                return ResourceManager.GetString("Region, city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &amp; where.
        /// </summary>
        internal static string Term___address_of_action {
            get {
                return ResourceManager.GetString("Term & address of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and name.
        /// </summary>
        internal static string Term___name_of_action {
            get {
                return ResourceManager.GetString("Term & name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of action.
        /// </summary>
        internal static string Term_of_action {
            get {
                return ResourceManager.GetString("Term of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update action.
        /// </summary>
        internal static string Update_action {
            get {
                return ResourceManager.GetString("Update action", resourceCulture);
            }
        }
    }
}
