//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogtrekkingCzApp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogtrekkingCzApp.Shared.ResourceFiles.Resource.cs-CZ", typeof(Resource_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat novou akci.
        /// </summary>
        internal static string Action_Create_AddNewAction {
            get {
                return ResourceManager.GetString("Action.Create.AddNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podat přihlášku.
        /// </summary>
        internal static string Action_CreateEntry {
            get {
                return ResourceManager.GetString("Action.CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber kategorii.
        /// </summary>
        internal static string Action_CreateEntry_Category_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Category.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psi.
        /// </summary>
        internal static string Action_CreateEntry_Dogs {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podat přihlášku na akci: .
        /// </summary>
        internal static string Action_CreateEntry_For_Action {
            get {
                return ResourceManager.GetString("Action.CreateEntry.For.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámky.
        /// </summary>
        internal static string Action_CreateEntry_Notes {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní.
        /// </summary>
        internal static string Action_CreateEntry_Person {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Action_CreateEntry_Person_Email {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Action_CreateEntry_Person_Name {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilní telefon.
        /// </summary>
        internal static string Action_CreateEntry_Person_Phone {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Action_CreateEntry_Person_Surname {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber závod.
        /// </summary>
        internal static string Action_CreateEntry_Race_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Race.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závod a kategorie.
        /// </summary>
        internal static string Action_CreateEntry_RaceCategory {
            get {
                return ResourceManager.GetString("Action.CreateEntry.RaceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat přihlášku.
        /// </summary>
        internal static string Action_CreateEntry_Submit {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrnutí.
        /// </summary>
        internal static string Action_CreateEntry_Summary {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat akci.
        /// </summary>
        internal static string Action_Delete_DeleteAction {
            get {
                return ResourceManager.GetString("Action.Delete.DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecné.
        /// </summary>
        internal static string Action_Manage_General {
            get {
                return ResourceManager.GetString("Action.Manage.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozice.
        /// </summary>
        internal static string Action_Manage_Location {
            get {
                return ResourceManager.GetString("Action.Manage.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závody.
        /// </summary>
        internal static string Action_Manage_Races {
            get {
                return ResourceManager.GetString("Action.Manage.Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledky.
        /// </summary>
        internal static string Action_Results {
            get {
                return ResourceManager.GetString("Action.Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat přihlášku.
        /// </summary>
        internal static string Action_SendEntry {
            get {
                return ResourceManager.GetString("Action.SendEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit akci.
        /// </summary>
        internal static string Action_Update_UpdateAction {
            get {
                return ResourceManager.GetString("Action.Update.UpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat akci.
        /// </summary>
        internal static string Actions_AddAction {
            get {
                return ResourceManager.GetString("Actions.AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny akce, dle datumu.
        /// </summary>
        internal static string Actions_AllByDate {
            get {
                return ResourceManager.GetString("Actions.AllByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficiální, schválené akce, dle datumu.
        /// </summary>
        internal static string Actions_ApprovedAndTermLockedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedAndTermLockedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválené, dle datumu.
        /// </summary>
        internal static string Actions_ApprovedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypsané závody.
        /// </summary>
        internal static string Actions_EnrolledRaces {
            get {
                return ResourceManager.GetString("Actions.EnrolledRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co a kým.
        /// </summary>
        internal static string Actions_Name_DescriptionOfAction {
            get {
                return ResourceManager.GetString("Actions.Name&DescriptionOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kdy a kde.
        /// </summary>
        internal static string Actions_Term_AddressOfAction {
            get {
                return ResourceManager.GetString("Actions.Term&AddressOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string Add_new_action {
            get {
                return ResourceManager.GetString("Add new action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit akci.
        /// </summary>
        internal static string Add_Update_action {
            get {
                return ResourceManager.GetString("Add/Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné.
        /// </summary>
        internal static string AuthorizationRoleType_None {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastník.
        /// </summary>
        internal static string AuthorizationRoleType_Owner {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        internal static string AuthorizationRoleType_User {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string Delete_action {
            get {
                return ResourceManager.GetString("Delete action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string Description_of_action {
            get {
                return ResourceManager.GetString("Description of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        internal static string Dog_Manage_Birthday {
            get {
                return ResourceManager.GetString("Dog.Manage.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záchranný kontakt.
        /// </summary>
        internal static string Dog_Manage_Contact {
            get {
                return ResourceManager.GetString("Dog.Manage.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum úmrtí.
        /// </summary>
        internal static string Dog_Manage_Decease {
            get {
                return ResourceManager.GetString("Dog.Manage.Decease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chovná stanice.
        /// </summary>
        internal static string Dog_Manage_Kennel {
            get {
                return ResourceManager.GetString("Dog.Manage.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Dog_Manage_Name {
            get {
                return ResourceManager.GetString("Dog.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastník.
        /// </summary>
        internal static string Dog_Manage_Owner {
            get {
                return ResourceManager.GetString("Dog.Manage.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Dog_Manage_Pedigree {
            get {
                return ResourceManager.GetString("Dog.Manage.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo čipu.
        /// </summary>
        internal static string Dogs_Chip {
            get {
                return ResourceManager.GetString("Dogs.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chovná stanice.
        /// </summary>
        internal static string Dogs_Kennel {
            get {
                return ResourceManager.GetString("Dogs.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Dogs_Name {
            get {
                return ResourceManager.GetString("Dogs.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Dogs_Pedigree {
            get {
                return ResourceManager.GetString("Dogs.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string InputTime_ClearTime {
            get {
                return ResourceManager.GetString("InputTime.ClearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dny.
        /// </summary>
        internal static string InputTime_Dayes {
            get {
                return ResourceManager.GetString("InputTime.Dayes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dny.
        /// </summary>
        internal static string InputTime_Days {
            get {
                return ResourceManager.GetString("InputTime.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hod.
        /// </summary>
        internal static string InputTime_Hours {
            get {
                return ResourceManager.GetString("InputTime.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string InputTime_Minutes {
            get {
                return ResourceManager.GetString("InputTime.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sek.
        /// </summary>
        internal static string InputTime_Seconds {
            get {
                return ResourceManager.GetString("InputTime.Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrávám ....
        /// </summary>
        internal static string Loading____ {
            get {
                return ResourceManager.GetString("Loading ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence psů.
        /// </summary>
        internal static string Menu_Dogs {
            get {
                return ResourceManager.GetString("Menu.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášky.
        /// </summary>
        internal static string Menu_Entries {
            get {
                return ResourceManager.GetString("Menu.Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string Name_of_action {
            get {
                return ResourceManager.GetString("Name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region, město.
        /// </summary>
        internal static string Region__city {
            get {
                return ResourceManager.GetString("Region, city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odešli.
        /// </summary>
        internal static string Results_AddResult_Submit {
            get {
                return ResourceManager.GetString("Results.AddResult.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidej výsledek.
        /// </summary>
        internal static string Results_Manage_Add {
            get {
                return ResourceManager.GetString("Results.Manage.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cíl.
        /// </summary>
        internal static string Results_Manage_Add_Finish {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Results_Manage_Add_Firstname {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Results_Manage_Add_Lastname_ {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Lastname ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Results_Manage_Add_Start {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín a název.
        /// </summary>
        internal static string Term___name_of_action {
            get {
                return ResourceManager.GetString("Term & name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín akce.
        /// </summary>
        internal static string Term_of_action {
            get {
                return ResourceManager.GetString("Term of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string Update_action {
            get {
                return ResourceManager.GetString("Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        internal static string UserProfile_Manage_City {
            get {
                return ResourceManager.GetString("UserProfile.Manage.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Země.
        /// </summary>
        internal static string UserProfile_Manage_Country {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserProfile_Manage_Email {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křestní jméno.
        /// </summary>
        internal static string UserProfile_Manage_Name {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přezdívka.
        /// </summary>
        internal static string UserProfile_Manage_Nickname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string UserProfile_Manage_Phone {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string UserProfile_Manage_Region {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        internal static string UserProfile_Manage_Street {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        internal static string UserProfile_Manage_Submit {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string UserProfile_Manage_Surname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Surname", resourceCulture);
            }
        }
    }
}
