//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsOnTrailApp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogsOnTrailApp.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new action.
        /// </summary>
        internal static string Action_Create_AddNewAction {
            get {
                return ResourceManager.GetString("Action.Create.AddNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create entry.
        /// </summary>
        internal static string Action_CreateEntry {
            get {
                return ResourceManager.GetString("Action.CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --== Select category ==--.
        /// </summary>
        internal static string Action_CreateEntry_Category_SelectCategory {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Category.SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string Action_CreateEntry_Category_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Category.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs.
        /// </summary>
        internal static string Action_CreateEntry_Dogs {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dog.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_AddNewDog {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.AddNewDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Age {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Chip {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Name {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedigree.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Pedigree {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of vacc against rabies.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Vaccinations_AgainstRabies {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Vaccinations.AgainstRabies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create entry for action: .
        /// </summary>
        internal static string Action_CreateEntry_For_Action {
            get {
                return ResourceManager.GetString("Action.CreateEntry.For.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Action_CreateEntry_Notes {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Action_CreateEntry_Person {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressCity {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressStreet {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressZipCode {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Action_CreateEntry_Person_Birthday {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Action_CreateEntry_Person_Email {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Action_CreateEntry_Person_Name {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePhone.
        /// </summary>
        internal static string Action_CreateEntry_Person_Phone {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Action_CreateEntry_Person_Surname {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select race.
        /// </summary>
        internal static string Action_CreateEntry_Race_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Race.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --== Select race ==--.
        /// </summary>
        internal static string Action_CreateEntry_Race_SelectRace {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Race.SelectRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race &amp; category.
        /// </summary>
        internal static string Action_CreateEntry_RaceCategory {
            get {
                return ResourceManager.GetString("Action.CreateEntry.RaceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send entry form.
        /// </summary>
        internal static string Action_CreateEntry_Submit {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Action_CreateEntry_Summary {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action.
        /// </summary>
        internal static string Action_Delete_DeleteAction {
            get {
                return ResourceManager.GetString("Action.Delete.DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying sale.
        /// </summary>
        internal static string Action_Manage_DefineAccompanyingSale {
            get {
                return ResourceManager.GetString("Action.Manage.DefineAccompanyingSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Action_Manage_General {
            get {
                return ResourceManager.GetString("Action.Manage.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Action_Manage_Location {
            get {
                return ResourceManager.GetString("Action.Manage.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string Action_Manage_Races {
            get {
                return ResourceManager.GetString("Action.Manage.Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Action_Results {
            get {
                return ResourceManager.GetString("Action.Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send entry.
        /// </summary>
        internal static string Action_SendEntry {
            get {
                return ResourceManager.GetString("Action.SendEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update action.
        /// </summary>
        internal static string Action_Update_UpdateAction {
            get {
                return ResourceManager.GetString("Action.Update.UpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add action.
        /// </summary>
        internal static string Actions_AddAction {
            get {
                return ResourceManager.GetString("Actions.AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All, by date.
        /// </summary>
        internal static string Actions_AllByDate {
            get {
                return ResourceManager.GetString("Actions.AllByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved and term locked, by date.
        /// </summary>
        internal static string Actions_ApprovedAndTermLockedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedAndTermLockedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved, by date.
        /// </summary>
        internal static string Actions_ApprovedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled races.
        /// </summary>
        internal static string Actions_EnrolledRaces {
            get {
                return ResourceManager.GetString("Actions.EnrolledRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact mail.
        /// </summary>
        internal static string Actions_Manage_MailContact {
            get {
                return ResourceManager.GetString("Actions.Manage.MailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What &amp; who.
        /// </summary>
        internal static string Actions_Name_DescriptionOfAction {
            get {
                return ResourceManager.GetString("Actions.Name&DescriptionOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Actions_Races_Categories {
            get {
                return ResourceManager.GetString("Actions.Races.Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill using official DogMarathon template.
        /// </summary>
        internal static string Actions_Races_FillOfficialDogMarathonRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillOfficialDogMarathonRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill using official DogTrekking template.
        /// </summary>
        internal static string Actions_Races_FillOfficialDogTrekkingRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillOfficialDogTrekkingRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill using Short template.
        /// </summary>
        internal static string Actions_Races_FillShortRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillShortRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits of race.
        /// </summary>
        internal static string Actions_Races_Limits {
            get {
                return ResourceManager.GetString("Actions.Races.Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal age of a dog in months.
        /// </summary>
        internal static string Actions_Races_Limits_MinimalAgeOfDogForRace {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.MinimalAgeOfDogForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal age of a racer.
        /// </summary>
        internal static string Actions_Races_Limits_MinimalAgeOfRacerForRace {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.MinimalAgeOfRacerForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With dogs.
        /// </summary>
        internal static string Actions_Races_Limits_WithDogs {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.WithDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Actions_Races_Name {
            get {
                return ResourceManager.GetString("Actions.Races.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment definitions.
        /// </summary>
        internal static string Actions_Races_Payments {
            get {
                return ResourceManager.GetString("Actions.Races.Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Actions_Sale_Colors {
            get {
                return ResourceManager.GetString("Actions.Sale.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Actions_Sale_Currency {
            get {
                return ResourceManager.GetString("Actions.Sale.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Actions_Sale_Description {
            get {
                return ResourceManager.GetString("Actions.Sale.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of item.
        /// </summary>
        internal static string Actions_Sale_Name {
            get {
                return ResourceManager.GetString("Actions.Sale.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Actions_Sale_Price {
            get {
                return ResourceManager.GetString("Actions.Sale.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        internal static string Actions_Sale_Sizes {
            get {
                return ResourceManager.GetString("Actions.Sale.Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        internal static string Actions_Sale_Variants {
            get {
                return ResourceManager.GetString("Actions.Sale.Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        internal static string Actions_Sales_AddNewItem {
            get {
                return ResourceManager.GetString("Actions.Sales.AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new t-shirt item.
        /// </summary>
        internal static string Actions_Sales_AddNewTShirtItem {
            get {
                return ResourceManager.GetString("Actions.Sales.AddNewTShirtItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &amp; where.
        /// </summary>
        internal static string Actions_Term_AddressOfAction {
            get {
                return ResourceManager.GetString("Actions.Term&AddressOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new action.
        /// </summary>
        internal static string Add_new_action {
            get {
                return ResourceManager.GetString("Add new action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update action.
        /// </summary>
        internal static string Add_Update_action {
            get {
                return ResourceManager.GetString("Add/Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AuthorizationRoleType_None {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string AuthorizationRoleType_Owner {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AuthorizationRoleType_User {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action.
        /// </summary>
        internal static string Delete_action {
            get {
                return ResourceManager.GetString("Delete action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of action.
        /// </summary>
        internal static string Description_of_action {
            get {
                return ResourceManager.GetString("Description of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birthday.
        /// </summary>
        internal static string Dog_Manage_Birthday {
            get {
                return ResourceManager.GetString("Dog.Manage.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        internal static string Dog_Manage_Contact {
            get {
                return ResourceManager.GetString("Dog.Manage.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of decease.
        /// </summary>
        internal static string Dog_Manage_Decease {
            get {
                return ResourceManager.GetString("Dog.Manage.Decease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennel.
        /// </summary>
        internal static string Dog_Manage_Kennel {
            get {
                return ResourceManager.GetString("Dog.Manage.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dog_Manage_Name {
            get {
                return ResourceManager.GetString("Dog.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Dog_Manage_Owner {
            get {
                return ResourceManager.GetString("Dog.Manage.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedigree.
        /// </summary>
        internal static string Dog_Manage_Pedigree {
            get {
                return ResourceManager.GetString("Dog.Manage.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip number.
        /// </summary>
        internal static string Dogs_Chip {
            get {
                return ResourceManager.GetString("Dogs.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennel.
        /// </summary>
        internal static string Dogs_Kennel {
            get {
                return ResourceManager.GetString("Dogs.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dogs_Name {
            get {
                return ResourceManager.GetString("Dogs.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedigree.
        /// </summary>
        internal static string Dogs_Pedigree {
            get {
                return ResourceManager.GetString("Dogs.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string InputTime_ClearTime {
            get {
                return ResourceManager.GetString("InputTime.ClearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayes.
        /// </summary>
        internal static string InputTime_Dayes {
            get {
                return ResourceManager.GetString("InputTime.Dayes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string InputTime_Days {
            get {
                return ResourceManager.GetString("InputTime.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs.
        /// </summary>
        internal static string InputTime_Hours {
            get {
                return ResourceManager.GetString("InputTime.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string InputTime_Minutes {
            get {
                return ResourceManager.GetString("InputTime.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string InputTime_Months {
            get {
                return ResourceManager.GetString("InputTime.Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        internal static string InputTime_Seconds {
            get {
                return ResourceManager.GetString("InputTime.Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string InputTime_Years {
            get {
                return ResourceManager.GetString("InputTime.Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string Loading____ {
            get {
                return ResourceManager.GetString("Loading ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs list.
        /// </summary>
        internal static string Menu_Dogs {
            get {
                return ResourceManager.GetString("Menu.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string Menu_Entries {
            get {
                return ResourceManager.GetString("Menu.Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid minimal age of dog for this race.
        /// </summary>
        internal static string Messages_Limits_Failed_MinimalAgeOfDogForRace {
            get {
                return ResourceManager.GetString("Messages.Limits.Failed.MinimalAgeOfDogForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal age for dog for this race in dayes is.
        /// </summary>
        internal static string Messages_Limits_Info_MinimalAgeOfDogForRaceInDaysIs {
            get {
                return ResourceManager.GetString("Messages.Limits.Info.MinimalAgeOfDogForRaceInDaysIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_of_action {
            get {
                return ResourceManager.GetString("Name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region, city.
        /// </summary>
        internal static string Region__city {
            get {
                return ResourceManager.GetString("Region, city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Results_AddResult_Submit {
            get {
                return ResourceManager.GetString("Results.AddResult.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add result.
        /// </summary>
        internal static string Results_Manage_Add {
            get {
                return ResourceManager.GetString("Results.Manage.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Results_Manage_Add_Finish {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Results_Manage_Add_Firstname {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Results_Manage_Add_Lastname {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Results_Manage_Add_Lastname_ {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Lastname ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Results_Manage_Add_Start {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and name.
        /// </summary>
        internal static string Term___name_of_action {
            get {
                return ResourceManager.GetString("Term & name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of action.
        /// </summary>
        internal static string Term_of_action {
            get {
                return ResourceManager.GetString("Term of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update action.
        /// </summary>
        internal static string Update_action {
            get {
                return ResourceManager.GetString("Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string UserProfile_Manage_City {
            get {
                return ResourceManager.GetString("UserProfile.Manage.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string UserProfile_Manage_Country {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserProfile_Manage_Email {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string UserProfile_Manage_Name {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string UserProfile_Manage_Nickname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string UserProfile_Manage_Phone {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string UserProfile_Manage_Region {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string UserProfile_Manage_Street {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string UserProfile_Manage_Submit {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string UserProfile_Manage_Surname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Surname", resourceCulture);
            }
        }
    }
}
