//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnTrailApp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetsOnTrailApp.Shared.ResourceFiles.Resource.cs-CZ", typeof(Resource_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola/sdílení polohy.
        /// </summary>
        internal static string Action_Checkpoint {
            get {
                return ResourceManager.GetString("Action.Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat novou akci.
        /// </summary>
        internal static string Action_Create_AddNewAction {
            get {
                return ResourceManager.GetString("Action.Create.AddNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podat přihlášku.
        /// </summary>
        internal static string Action_CreateEntry {
            get {
                return ResourceManager.GetString("Action.CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --== Vyber kategorii ==--.
        /// </summary>
        internal static string Action_CreateEntry_Category_SelectCategory {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Category.SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber kategorii.
        /// </summary>
        internal static string Action_CreateEntry_Category_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Category.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psi.
        /// </summary>
        internal static string Action_CreateEntry_Dogs {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidej psa.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_AddNewDog {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.AddNewDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Věk.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Age {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čip.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Chip {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Name {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Pedigree {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum očkování proti vzteklině.
        /// </summary>
        internal static string Action_CreateEntry_Dogs_Vaccinations_AgainstRabies {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Dogs.Vaccinations.AgainstRabies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podat přihlášku na akci: .
        /// </summary>
        internal static string Action_CreateEntry_For_Action {
            get {
                return ResourceManager.GetString("Action.CreateEntry.For.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámky.
        /// </summary>
        internal static string Action_CreateEntry_Notes {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní.
        /// </summary>
        internal static string Action_CreateEntry_Person {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressCity {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressStreet {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        internal static string Action_CreateEntry_Person_AddressZipCode {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.AddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        internal static string Action_CreateEntry_Person_Birthday {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Action_CreateEntry_Person_Email {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Action_CreateEntry_Person_Name {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilní telefon.
        /// </summary>
        internal static string Action_CreateEntry_Person_Phone {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Action_CreateEntry_Person_Surname {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Person.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber závod.
        /// </summary>
        internal static string Action_CreateEntry_Race_Selection {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Race.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --== Vyber závod ==--.
        /// </summary>
        internal static string Action_CreateEntry_Race_SelectRace {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Race.SelectRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závod a kategorie.
        /// </summary>
        internal static string Action_CreateEntry_RaceCategory {
            get {
                return ResourceManager.GetString("Action.CreateEntry.RaceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat přihlášku.
        /// </summary>
        internal static string Action_CreateEntry_Submit {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrnutí.
        /// </summary>
        internal static string Action_CreateEntry_Summary {
            get {
                return ResourceManager.GetString("Action.CreateEntry.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat akci.
        /// </summary>
        internal static string Action_Delete_DeleteAction {
            get {
                return ResourceManager.GetString("Action.Delete.DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválit plnou platbu.
        /// </summary>
        internal static string Action_Manage_AcceptPayment {
            get {
                return ResourceManager.GetString("Action.Manage.AcceptPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválit přihlášku.
        /// </summary>
        internal static string Action_Manage_AcceptRegistration {
            get {
                return ResourceManager.GetString("Action.Manage.AcceptRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Action_Manage_Actions {
            get {
                return ResourceManager.GetString("Action.Manage.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Action_Manage_Category {
            get {
                return ResourceManager.GetString("Action.Manage.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat příchozí průchody kontrolou.
        /// </summary>
        internal static string Action_Manage_Checkpoints {
            get {
                return ResourceManager.GetString("Action.Manage.Checkpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doprovodný prodej.
        /// </summary>
        internal static string Action_Manage_DefineAccompanyingSale {
            get {
                return ResourceManager.GetString("Action.Manage.DefineAccompanyingSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat přihlášky.
        /// </summary>
        internal static string Action_Manage_Entries {
            get {
                return ResourceManager.GetString("Action.Manage.Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecné.
        /// </summary>
        internal static string Action_Manage_General {
            get {
                return ResourceManager.GetString("Action.Manage.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozice.
        /// </summary>
        internal static string Action_Manage_Location {
            get {
                return ResourceManager.GetString("Action.Manage.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat platby.
        /// </summary>
        internal static string Action_Manage_ManagePayments {
            get {
                return ResourceManager.GetString("Action.Manage.ManagePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Action_Manage_Name {
            get {
                return ResourceManager.GetString("Action.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platby.
        /// </summary>
        internal static string Action_Manage_Payments {
            get {
                return ResourceManager.GetString("Action.Manage.Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazlíci.
        /// </summary>
        internal static string Action_Manage_Pets {
            get {
                return ResourceManager.GetString("Action.Manage.Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závod.
        /// </summary>
        internal static string Action_Manage_Race {
            get {
                return ResourceManager.GetString("Action.Manage.Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závody.
        /// </summary>
        internal static string Action_Manage_Races {
            get {
                return ResourceManager.GetString("Action.Manage.Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        internal static string Action_Manage_Registrations {
            get {
                return ResourceManager.GetString("Action.Manage.Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schvalování registrací.
        /// </summary>
        internal static string Action_Manage_RegistrationToAccept {
            get {
                return ResourceManager.GetString("Action.Manage.RegistrationToAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Action_Manage_Surname {
            get {
                return ResourceManager.GetString("Action.Manage.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledky.
        /// </summary>
        internal static string Action_Results {
            get {
                return ResourceManager.GetString("Action.Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat přihlášku.
        /// </summary>
        internal static string Action_SendEntry {
            get {
                return ResourceManager.GetString("Action.SendEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit akci.
        /// </summary>
        internal static string Action_Update_UpdateAction {
            get {
                return ResourceManager.GetString("Action.Update.UpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat akci.
        /// </summary>
        internal static string Actions_AddAction {
            get {
                return ResourceManager.GetString("Actions.AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny akce, dle datumu.
        /// </summary>
        internal static string Actions_AllByDate {
            get {
                return ResourceManager.GetString("Actions.AllByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficiální, schválené akce, dle datumu.
        /// </summary>
        internal static string Actions_ApprovedAndTermLockedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedAndTermLockedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválené, dle datumu.
        /// </summary>
        internal static string Actions_ApprovedByDate {
            get {
                return ResourceManager.GetString("Actions.ApprovedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypsané závody.
        /// </summary>
        internal static string Actions_EnrolledRaces {
            get {
                return ResourceManager.GetString("Actions.EnrolledRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailový kontakt.
        /// </summary>
        internal static string Actions_Manage_MailContact {
            get {
                return ResourceManager.GetString("Actions.Manage.MailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co a kým.
        /// </summary>
        internal static string Actions_Name_DescriptionOfAction {
            get {
                return ResourceManager.GetString("Actions.Name&DescriptionOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Actions_Races_Categories {
            get {
                return ResourceManager.GetString("Actions.Races.Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit dle oficiální DogMarathon šablony.
        /// </summary>
        internal static string Actions_Races_FillOfficialDogMarathonRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillOfficialDogMarathonRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit dle oficiální DogTrekking šablony.
        /// </summary>
        internal static string Actions_Races_FillOfficialDogTrekkingRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillOfficialDogTrekkingRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit dle šablony pro závody typu Short.
        /// </summary>
        internal static string Actions_Races_FillShortRace {
            get {
                return ResourceManager.GetString("Actions.Races.FillShortRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omezení závodu.
        /// </summary>
        internal static string Actions_Races_Limits {
            get {
                return ResourceManager.GetString("Actions.Races.Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimální věk psa v měsících.
        /// </summary>
        internal static string Actions_Races_Limits_MinimalAgeOfDogForRace {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.MinimalAgeOfDogForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimální věk závodníka.
        /// </summary>
        internal static string Actions_Races_Limits_MinimalAgeOfRacerForRace {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.MinimalAgeOfRacerForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se psy.
        /// </summary>
        internal static string Actions_Races_Limits_WithDogs {
            get {
                return ResourceManager.GetString("Actions.Races.Limits.WithPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string Actions_Races_Name {
            get {
                return ResourceManager.GetString("Actions.Races.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definice plateb.
        /// </summary>
        internal static string Actions_Races_Payments {
            get {
                return ResourceManager.GetString("Actions.Races.Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barvy.
        /// </summary>
        internal static string Actions_Sale_Colors {
            get {
                return ResourceManager.GetString("Actions.Sale.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        internal static string Actions_Sale_Currency {
            get {
                return ResourceManager.GetString("Actions.Sale.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisek.
        /// </summary>
        internal static string Actions_Sale_Description {
            get {
                return ResourceManager.GetString("Actions.Sale.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název položky.
        /// </summary>
        internal static string Actions_Sale_Name {
            get {
                return ResourceManager.GetString("Actions.Sale.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        internal static string Actions_Sale_Price {
            get {
                return ResourceManager.GetString("Actions.Sale.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikosti.
        /// </summary>
        internal static string Actions_Sale_Sizes {
            get {
                return ResourceManager.GetString("Actions.Sale.Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varianty.
        /// </summary>
        internal static string Actions_Sale_Variants {
            get {
                return ResourceManager.GetString("Actions.Sale.Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat novou položku.
        /// </summary>
        internal static string Actions_Sales_AddNewItem {
            get {
                return ResourceManager.GetString("Actions.Sales.AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat položku typu tričko.
        /// </summary>
        internal static string Actions_Sales_AddNewTShirtItem {
            get {
                return ResourceManager.GetString("Actions.Sales.AddNewTShirtItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kdy a kde.
        /// </summary>
        internal static string Actions_Term_AddressOfAction {
            get {
                return ResourceManager.GetString("Actions.Term&AddressOfAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string Add_new_action {
            get {
                return ResourceManager.GetString("Add new action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit akci.
        /// </summary>
        internal static string Add_Update_action {
            get {
                return ResourceManager.GetString("Add/Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválené registrace.
        /// </summary>
        internal static string Admin_Manage_Registrations {
            get {
                return ResourceManager.GetString("Admin.Manage.Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné.
        /// </summary>
        internal static string AuthorizationRoleType_None {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastník.
        /// </summary>
        internal static string AuthorizationRoleType_Owner {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        internal static string AuthorizationRoleType_User {
            get {
                return ResourceManager.GetString("AuthorizationRoleType.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Checkpoint_Action {
            get {
                return ResourceManager.GetString("Checkpoint.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoposílání.
        /// </summary>
        internal static string Checkpoint_AutoSend {
            get {
                return ResourceManager.GetString("Checkpoint.AutoSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola.
        /// </summary>
        internal static string Checkpoint_Checkpoint {
            get {
                return ResourceManager.GetString("Checkpoint.Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Checkpoint_Data {
            get {
                return ResourceManager.GetString("Checkpoint.Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum a čas.
        /// </summary>
        internal static string Checkpoint_DateTime {
            get {
                return ResourceManager.GetString("Checkpoint.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástroj pro sbírání aktuální polohy a odesílání stavu závodníků na trati..
        /// </summary>
        internal static string Checkpoint_Description {
            get {
                return ResourceManager.GetString("Checkpoint.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string Checkpoint_GPS {
            get {
                return ResourceManager.GetString("Checkpoint.GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string Checkpoint_Name {
            get {
                return ResourceManager.GetString("Checkpoint.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádný QR kód nebyl detekován.
        /// </summary>
        internal static string Checkpoint_NoQRDetected {
            get {
                return ResourceManager.GetString("Checkpoint.NoQRDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        internal static string Checkpoint_Note {
            get {
                return ResourceManager.GetString("Checkpoint.Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozice.
        /// </summary>
        internal static string Checkpoint_Position {
            get {
                return ResourceManager.GetString("Checkpoint.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR čtečka.
        /// </summary>
        internal static string Checkpoint_QrReader {
            get {
                return ResourceManager.GetString("Checkpoint.QrReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat data.
        /// </summary>
        internal static string Checkpoint_SendData {
            get {
                return ResourceManager.GetString("Checkpoint.SendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobraz detaily.
        /// </summary>
        internal static string Checkpoint_ShowDetails {
            get {
                return ResourceManager.GetString("Checkpoint.ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string Checkpoint_Time {
            get {
                return ResourceManager.GetString("Checkpoint.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Živá kontrola.
        /// </summary>
        internal static string Checkpoint_Title {
            get {
                return ResourceManager.GetString("Checkpoint.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎥 Není možné zpřístupnit video stream. Ujistěte se, že máte kameru pro tento web povolenou..
        /// </summary>
        internal static string Checkpoint_UnableToStartCameraForQrCodeReading {
            get {
                return ResourceManager.GetString("Checkpoint.UnableToStartCameraForQrCodeReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        internal static string Checkpoint_User {
            get {
                return ResourceManager.GetString("Checkpoint.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dní.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string Delete_action {
            get {
                return ResourceManager.GetString("Delete action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string Description_of_action {
            get {
                return ResourceManager.GetString("Description of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        internal static string Dog_Manage_Birthday {
            get {
                return ResourceManager.GetString("Dog.Manage.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záchranný kontakt.
        /// </summary>
        internal static string Dog_Manage_Contact {
            get {
                return ResourceManager.GetString("Dog.Manage.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum úmrtí.
        /// </summary>
        internal static string Dog_Manage_Decease {
            get {
                return ResourceManager.GetString("Dog.Manage.Decease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chovná stanice.
        /// </summary>
        internal static string Dog_Manage_Kennel {
            get {
                return ResourceManager.GetString("Dog.Manage.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Dog_Manage_Name {
            get {
                return ResourceManager.GetString("Dog.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastník.
        /// </summary>
        internal static string Dog_Manage_Owner {
            get {
                return ResourceManager.GetString("Dog.Manage.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Dog_Manage_Pedigree {
            get {
                return ResourceManager.GetString("Dog.Manage.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat psa.
        /// </summary>
        internal static string Dogs_AddDog {
            get {
                return ResourceManager.GetString("Dogs.AddDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo čipu.
        /// </summary>
        internal static string Dogs_Chip {
            get {
                return ResourceManager.GetString("Dogs.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chovná stanice.
        /// </summary>
        internal static string Dogs_Kennel {
            get {
                return ResourceManager.GetString("Dogs.Kennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Dogs_Name {
            get {
                return ResourceManager.GetString("Dogs.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Dogs_Pedigree {
            get {
                return ResourceManager.GetString("Dogs.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidovaní psi.
        /// </summary>
        internal static string Dogs_Title {
            get {
                return ResourceManager.GetString("Dogs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový.
        /// </summary>
        internal static string General_New {
            get {
                return ResourceManager.GetString("General.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string General_Save {
            get {
                return ResourceManager.GetString("General.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit mé pozice.
        /// </summary>
        internal static string Home_ManageMyPositions {
            get {
                return ResourceManager.GetString("Home.ManageMyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit můj profil.
        /// </summary>
        internal static string Home_ManageMyProfile {
            get {
                return ResourceManager.GetString("Home.ManageMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsi přihlášen.
        /// </summary>
        internal static string Home_YouAreNotLoggedIn {
            get {
                return ResourceManager.GetString("Home.YouAreNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string InputTime_ClearTime {
            get {
                return ResourceManager.GetString("InputTime.ClearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dny.
        /// </summary>
        internal static string InputTime_Dayes {
            get {
                return ResourceManager.GetString("InputTime.Dayes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dny.
        /// </summary>
        internal static string InputTime_Days {
            get {
                return ResourceManager.GetString("InputTime.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hod.
        /// </summary>
        internal static string InputTime_Hours {
            get {
                return ResourceManager.GetString("InputTime.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string InputTime_Minutes {
            get {
                return ResourceManager.GetString("InputTime.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc.
        /// </summary>
        internal static string InputTime_Months {
            get {
                return ResourceManager.GetString("InputTime.Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sek.
        /// </summary>
        internal static string InputTime_Seconds {
            get {
                return ResourceManager.GetString("InputTime.Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        internal static string InputTime_Years {
            get {
                return ResourceManager.GetString("InputTime.Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrávám ....
        /// </summary>
        internal static string Loading____ {
            get {
                return ResourceManager.GetString("Loading ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaběhnutí mazlíci.
        /// </summary>
        internal static string LostPets_Title {
            get {
                return ResourceManager.GetString("LostPets.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string Menu_Actions {
            get {
                return ResourceManager.GetString("Menu.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa akcí.
        /// </summary>
        internal static string Menu_ActionsMap {
            get {
                return ResourceManager.GetString("Menu.ActionsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdílení pozice.
        /// </summary>
        internal static string Menu_Checkpoint {
            get {
                return ResourceManager.GetString("Menu.Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence psů.
        /// </summary>
        internal static string Menu_Dogs {
            get {
                return ResourceManager.GetString("Menu.Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášky.
        /// </summary>
        internal static string Menu_Entries {
            get {
                return ResourceManager.GetString("Menu.Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazlíci.
        /// </summary>
        internal static string Menu_Pets {
            get {
                return ResourceManager.GetString("Menu.Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není splněn minimální věk psa pro tento závod.
        /// </summary>
        internal static string Messages_Limits_Failed_MinimalAgeOfDogForRace {
            get {
                return ResourceManager.GetString("Messages.Limits.Failed.MinimalAgeOfDogForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimální věk psa pro tento závod ve dnech je.
        /// </summary>
        internal static string Messages_Limits_Info_MinimalAgeOfDogForRaceInDaysIs {
            get {
                return ResourceManager.GetString("Messages.Limits.Info.MinimalAgeOfDogForRaceInDaysIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to měsíců.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string Name_of_action {
            get {
                return ResourceManager.GetString("Name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat mazlíka.
        /// </summary>
        internal static string Pets_AddPet {
            get {
                return ResourceManager.GetString("Pets.AddPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čip.
        /// </summary>
        internal static string Pets_Chip {
            get {
                return ResourceManager.GetString("Pets.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Můžeš zde zaevidovat své mazlíky. Uvidíš zde pouze své mazlíky, popř. mazlíky, které se hledají. Pokud někdo najde Tvého mazlíka - bude moci zde dohledat majitele a kontaktovat ho..
        /// </summary>
        internal static string Pets_Description {
            get {
                return ResourceManager.GetString("Pets.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Pets_Name {
            get {
                return ResourceManager.GetString("Pets.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plemeno.
        /// </summary>
        internal static string Pets_Pedigree {
            get {
                return ResourceManager.GetString("Pets.Pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence mazlíků.
        /// </summary>
        internal static string Pets_Title {
            get {
                return ResourceManager.GetString("Pets.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh.
        /// </summary>
        internal static string Pets_Type {
            get {
                return ResourceManager.GetString("Pets.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region, město.
        /// </summary>
        internal static string Region__city {
            get {
                return ResourceManager.GetString("Region, city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledky.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odešli.
        /// </summary>
        internal static string Results_AddResult_Submit {
            get {
                return ResourceManager.GetString("Results.AddResult.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cíl.
        /// </summary>
        internal static string Results_Finish {
            get {
                return ResourceManager.GetString("Results.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidej výsledek.
        /// </summary>
        internal static string Results_Manage_Add {
            get {
                return ResourceManager.GetString("Results.Manage.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cíl.
        /// </summary>
        internal static string Results_Manage_Add_Finish {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Results_Manage_Add_Firstname {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Results_Manage_Add_Lastname {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string Results_Manage_Add_Lastname_ {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Lastname ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Results_Manage_Add_Start {
            get {
                return ResourceManager.GetString("Results.Manage.Add.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Results_Start {
            get {
                return ResourceManager.GetString("Results.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení, jméno.
        /// </summary>
        internal static string Results_SurnameName {
            get {
                return ResourceManager.GetString("Results.SurnameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Časy.
        /// </summary>
        internal static string Results_Time {
            get {
                return ResourceManager.GetString("Results.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín a název.
        /// </summary>
        internal static string Term___name_of_action {
            get {
                return ResourceManager.GetString("Term & name of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín akce.
        /// </summary>
        internal static string Term_of_action {
            get {
                return ResourceManager.GetString("Term of action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string Update_action {
            get {
                return ResourceManager.GetString("Update action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava profilu.
        /// </summary>
        internal static string UserProfile_Manage {
            get {
                return ResourceManager.GetString("UserProfile.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        internal static string UserProfile_Manage_City {
            get {
                return ResourceManager.GetString("UserProfile.Manage.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Země.
        /// </summary>
        internal static string UserProfile_Manage_Country {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserProfile_Manage_Email {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křestní jméno.
        /// </summary>
        internal static string UserProfile_Manage_Name {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přezdívka.
        /// </summary>
        internal static string UserProfile_Manage_Nickname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string UserProfile_Manage_Phone {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string UserProfile_Manage_Region {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        internal static string UserProfile_Manage_Street {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        internal static string UserProfile_Manage_Submit {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string UserProfile_Manage_Surname {
            get {
                return ResourceManager.GetString("UserProfile.Manage.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mí mazlíci.
        /// </summary>
        internal static string UserProfile_MyPets {
            get {
                return ResourceManager.GetString("UserProfile.MyPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Věk.
        /// </summary>
        internal static string UserProfile_MyPets_Age {
            get {
                return ResourceManager.GetString("UserProfile.MyPets.Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čip.
        /// </summary>
        internal static string UserProfile_MyPets_Chip {
            get {
                return ResourceManager.GetString("UserProfile.MyPets.Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string UserProfile_MyPets_Name {
            get {
                return ResourceManager.GetString("UserProfile.MyPets.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očkování.
        /// </summary>
        internal static string UserProfile_MyPets_Vaccinations {
            get {
                return ResourceManager.GetString("UserProfile.MyPets.Vaccinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roků.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
